# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/challenge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protobuf/challenge.proto\x12\x17\x63hainflag.ctf.challenge\"]\n\x04Info\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x13\n\x0bshow_source\x18\x02 \x01(\x08\x12\x14\n\x0csolved_event\x18\x03 \x01(\t\x12\x15\n\rdeployed_addr\x18\x04 \x01(\t\";\n\nPlayground\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\",\n\x08\x43ontract\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07tx_hash\x18\x02 \x01(\t\"\x14\n\x04\x46lag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\t\")\n\x05\x45vent\x12\x14\n\x07tx_hash\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_tx_hash\"|\n\nSourceCode\x12?\n\x06source\x18\x01 \x03(\x0b\x32/.chainflag.ctf.challenge.SourceCode.SourceEntry\x1a-\n\x0bSourceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty2\xa9\x03\n\tChallenge\x12Q\n\x10GetChallengeInfo\x12\x1e.chainflag.ctf.challenge.Empty\x1a\x1d.chainflag.ctf.challenge.Info\x12T\n\rNewPlayground\x12\x1e.chainflag.ctf.challenge.Empty\x1a#.chainflag.ctf.challenge.Playground\x12S\n\x0e\x44\x65ployContract\x12\x1e.chainflag.ctf.challenge.Empty\x1a!.chainflag.ctf.challenge.Contract\x12H\n\x07GetFlag\x12\x1e.chainflag.ctf.challenge.Event\x1a\x1d.chainflag.ctf.challenge.Flag\x12T\n\rGetSourceCode\x12\x1e.chainflag.ctf.challenge.Empty\x1a#.chainflag.ctf.challenge.SourceCodeB\x0bZ\tchallengeb\x06proto3')



_INFO = DESCRIPTOR.message_types_by_name['Info']
_PLAYGROUND = DESCRIPTOR.message_types_by_name['Playground']
_CONTRACT = DESCRIPTOR.message_types_by_name['Contract']
_FLAG = DESCRIPTOR.message_types_by_name['Flag']
_EVENT = DESCRIPTOR.message_types_by_name['Event']
_SOURCECODE = DESCRIPTOR.message_types_by_name['SourceCode']
_SOURCECODE_SOURCEENTRY = _SOURCECODE.nested_types_by_name['SourceEntry']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Info)
  })
_sym_db.RegisterMessage(Info)

Playground = _reflection.GeneratedProtocolMessageType('Playground', (_message.Message,), {
  'DESCRIPTOR' : _PLAYGROUND,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Playground)
  })
_sym_db.RegisterMessage(Playground)

Contract = _reflection.GeneratedProtocolMessageType('Contract', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACT,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Contract)
  })
_sym_db.RegisterMessage(Contract)

Flag = _reflection.GeneratedProtocolMessageType('Flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Flag)
  })
_sym_db.RegisterMessage(Flag)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Event)
  })
_sym_db.RegisterMessage(Event)

SourceCode = _reflection.GeneratedProtocolMessageType('SourceCode', (_message.Message,), {

  'SourceEntry' : _reflection.GeneratedProtocolMessageType('SourceEntry', (_message.Message,), {
    'DESCRIPTOR' : _SOURCECODE_SOURCEENTRY,
    '__module__' : 'protobuf.challenge_pb2'
    # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.SourceCode.SourceEntry)
    })
  ,
  'DESCRIPTOR' : _SOURCECODE,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.SourceCode)
  })
_sym_db.RegisterMessage(SourceCode)
_sym_db.RegisterMessage(SourceCode.SourceEntry)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protobuf.challenge_pb2'
  # @@protoc_insertion_point(class_scope:chainflag.ctf.challenge.Empty)
  })
_sym_db.RegisterMessage(Empty)

_CHALLENGE = DESCRIPTOR.services_by_name['Challenge']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\tchallenge'
  _SOURCECODE_SOURCEENTRY._options = None
  _SOURCECODE_SOURCEENTRY._serialized_options = b'8\001'
  _INFO._serialized_start=53
  _INFO._serialized_end=146
  _PLAYGROUND._serialized_start=148
  _PLAYGROUND._serialized_end=207
  _CONTRACT._serialized_start=209
  _CONTRACT._serialized_end=253
  _FLAG._serialized_start=255
  _FLAG._serialized_end=275
  _EVENT._serialized_start=277
  _EVENT._serialized_end=318
  _SOURCECODE._serialized_start=320
  _SOURCECODE._serialized_end=444
  _SOURCECODE_SOURCEENTRY._serialized_start=399
  _SOURCECODE_SOURCEENTRY._serialized_end=444
  _EMPTY._serialized_start=446
  _EMPTY._serialized_end=453
  _CHALLENGE._serialized_start=456
  _CHALLENGE._serialized_end=881
# @@protoc_insertion_point(module_scope)
