# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: protobuf/challenge.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class ChallengeServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/chainflag.ctf.challenge.Challenge"
		self._endpoints = {
			"GetChallengeInfo": Endpoint(
				service_name="Challenge",
				name="GetChallengeInfo",
				function=getattr(service, "GetChallengeInfo"),
				input=_sym_db.GetSymbol("chainflag.ctf.challenge.Empty"),
				output=_sym_db.GetSymbol("chainflag.ctf.challenge.Info"),
			),
			"NewPlayground": Endpoint(
				service_name="Challenge",
				name="NewPlayground",
				function=getattr(service, "NewPlayground"),
				input=_sym_db.GetSymbol("chainflag.ctf.challenge.Empty"),
				output=_sym_db.GetSymbol("chainflag.ctf.challenge.Playground"),
			),
			"DeployContract": Endpoint(
				service_name="Challenge",
				name="DeployContract",
				function=getattr(service, "DeployContract"),
				input=_sym_db.GetSymbol("chainflag.ctf.challenge.Empty"),
				output=_sym_db.GetSymbol("chainflag.ctf.challenge.Contract"),
			),
			"GetFlag": Endpoint(
				service_name="Challenge",
				name="GetFlag",
				function=getattr(service, "GetFlag"),
				input=_sym_db.GetSymbol("chainflag.ctf.challenge.Event"),
				output=_sym_db.GetSymbol("chainflag.ctf.challenge.Flag"),
			),
			"GetSourceCode": Endpoint(
				service_name="Challenge",
				name="GetSourceCode",
				function=getattr(service, "GetSourceCode"),
				input=_sym_db.GetSymbol("chainflag.ctf.challenge.Empty"),
				output=_sym_db.GetSymbol("chainflag.ctf.challenge.SourceCode"),
			),
		}

class ChallengeClient(TwirpClient):

	def GetChallengeInfo(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/chainflag.ctf.challenge.Challenge/GetChallengeInfo",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("chainflag.ctf.challenge.Info"),
			**kwargs,
		)

	def NewPlayground(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/chainflag.ctf.challenge.Challenge/NewPlayground",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("chainflag.ctf.challenge.Playground"),
			**kwargs,
		)

	def DeployContract(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/chainflag.ctf.challenge.Challenge/DeployContract",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("chainflag.ctf.challenge.Contract"),
			**kwargs,
		)

	def GetFlag(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/chainflag.ctf.challenge.Challenge/GetFlag",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("chainflag.ctf.challenge.Flag"),
			**kwargs,
		)

	def GetSourceCode(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/chainflag.ctf.challenge.Challenge/GetSourceCode",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("chainflag.ctf.challenge.SourceCode"),
			**kwargs,
		)
