[package]
name = "checkin"
version = "0.0.1"

[dependencies]
Sui = { local = "/root/.move/https___github_com_MystenLabs_sui_git_devnet/crates/sui-framework" }

[addresses]
checkin =  "0x0"
sui =  "0000000000000000000000000000000000000002"
